spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qma_db
    username: root
    password: ${db_password}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}

  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: ${jwt-secret-key}
